# Generated by Django 3.1.2 on 2020-10-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201013_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otro',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
