# Generated by Django 3.1.2 on 2020-10-17 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_otro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
