# Generated by Django 3.1.2 on 2020-10-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201017_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otro',
        ),
    ]
