# Generated by Django 3.1.2 on 2020-11-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tarjetasusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjetasusuario',
            old_name='user',
            new_name='id_user',
        ),
    ]
