# Generated by Django 3.1.2 on 2020-10-30 05:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=5)),
                ('cant', models.CharField(max_length=5)),
                ('precio', models.CharField(max_length=5)),
                ('id_trans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CardCatalog.transaccion')),
            ],
        ),
    ]
