# Generated by Django 3.1.2 on 2020-10-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardCatalog', '0003_auto_20201031_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tarjeta_transaccion',
        ),
    ]
