# Generated by Django 3.1.2 on 2020-10-31 08:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CardCatalog', '0004_delete_tarjeta_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjeta_transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('nombre_tarjeta', models.CharField(max_length=25)),
                ('fecha_expiracion', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('codigo', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('monto', models.CharField(max_length=25)),
                ('moneda', models.CharField(choices=[('DÓLARES', 'DÓLARES'), ('QUETZALES', 'QUETZALES')], max_length=10)),
                ('estado', models.CharField(choices=[('EXITOSO', 'EXITOSO'), ('FALLIDO', 'FALLIDO')], max_length=10)),
                ('id_trans', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CardCatalog.transaccion')),
            ],
        ),
    ]
