# Generated by Django 3.1.2 on 2020-11-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardCatalog', '0006_auto_20201031_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_transaccion',
            name='val_card',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
